### PR TITLE
Check for overlapping fields

### PR DESCRIPTION
**Pull request by pavelkryukov**

### CODE REVIEW

**Comment by aswaterman** [comment]
OK with you, @neelgala?

**Comment by pavelkryukov** [comment]
`jol rd rs1 jimm20 6..2=0x1b 1..0=3`.

Here rs1 and jimm20 overlap and create ambiguity, I have a disable unit test for that in https://github.com/riscv/riscv-opcodes/pull/119

**Comment by neelgala** [comment]
LGTM - @aswaterman please merge

**Comment by aswaterman** [comment]
yessir

**Pull request merged**
