### PR TITLE
updating opcodes of riscv-p-spec - v0.9.11 (c3409c8)

### PR DESCRIPTION
**Pull request by eflaner**
- Reorganized 'p' into sub-extensions as [described here](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#5-p-extension-subsets) 
    - created zpn, zpfs & zbpbo (along with appropriate 32 & 64 variants)
    - removed rv_p, rv64_p ( according to RISC-V sub-extension policy -- it's invalid )
- zbpbo 
    - [Replaced bitrevi with grevi](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#bitrevi-bit-reverse-immediate)) 
    - [Replaced BPICK with CMIX](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#111-bpick-bit-wise-pick)
- zpsf (zpsfoperand)
    - created zpsf as [specified in specification](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#52-zpsfoperand)
    - [SMMUL replacement in RV32 with MULH](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#42-rv32m-extension)
    - [MAXW ](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#112-maxw-32-bit-signed-word-maximum) and [MINW ](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#113-minw-32-bit-signed-word-minimum) removed (replaced with MAX and MIN of Zbb respectively)
    - [Removed SWAP8](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#7134-swap8-swap-byte-within-halfword) (replaced with REV8.H)
    - Removed [WEXT ](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#7181-wext-extract-word-from-64-bit) and [WEXTI](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#7180-wexti-extract-word-from-64-bit-immediate) (replaced with FSR and FSRI respectively)
- zpn
    - Removed CLO* variants 
    - Seperated [INSB](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#718-insb-insert-byte), [SRAI.u](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#7119-sraiu-rounding-shift-right-arithmetic-immediate) instructions into RV32 and RV64 equivalents
    - [PKBB32, PKTT32 removed](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#822-pkbb32-pkbt32-pktt32-pktb32) (Replaced by PACK and PACKU of Zbp respectively)
    - [PKTT16 and PKBB16 restricted to RV64](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#773-pkbb16-pkbt16-pktt16-pktb16) 
    - Added [CLROV](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#77-clrov-clear-ov-flag) and [RDOV](https://github.com/riscv/riscv-p-spec/blob/c3409c8edb7df262cb3db0ff323077120e5f7f04/P-ext-proposal.adoc#780-rdov-read-ov-flag)

### CODE REVIEW

**Comment by neelgala** [comment]
LGTM 
@aswaterman could you enable the workflow on this PR ? if they pass I think it can be merged.

**Comment by aswaterman** [comment]
Yeah, thanks for reviewing, @neelgala

**Comment by aswaterman** [comment]
@eflaner Did you ever make a Spike PR associated with these changes?  Spike no longer builds because it depends on the opcode definitions for the removed instructions like PKBB32.

Without a corresponding Spike PR, I'll have to revert this PR, since we can't make progress on other extensions in Spike in the meantime.

**Comment by aswaterman** [comment]
@scottj97 Do you think we should augment riscv-opcodes' CI flow to make sure that the HEAD of master on riscv-isa-sim can build with the generated encoding.h?  It couples these repos awkwardly, but it would prevent this kind of breakage going forward.

**Comment by scottj97** [comment]
> @scottj97 Do you think we should augment riscv-opcodes' CI flow to make sure that the HEAD of master on riscv-isa-sim can build with the generated encoding.h? It couples these repos awkwardly, but it would prevent this kind of breakage going forward.

Fortunately this is rare, and I think we have a suitable [workaround](https://github.com/riscv-software-src/riscv-isa-sim/pull/1234#discussion_r1092243338) for this one.

> For a change like this one, which both adds and deletes opcodes, we'd either need to stage it as multiple PRs, or allow the corresponding Spike PR to be merged before rerunning CI over here. Fortunately, this kind of PR is not the common case.

I don't think Spike should commit an `encoding.h` to its master if the source for that file is not yet in master here. We don't want a rebased PR here to invalidate the hashes that are permanently committed into Spike's history.

**Comment by aswaterman** [comment]
Reasonable.

**Comment by eflaner** [comment]
@aswaterman 

> @eflaner Did you ever make a Spike PR associated with these changes? Spike no longer builds because it depends on the opcode definitions for the removed instructions like PKBB32.

No PR was created in Spike for these changes. Neither am i aware of spike internals to make it compliant with 'latest' spike.   

> Without a corresponding Spike PR, I'll have to revert this PR, since we can't make progress on other extensions in Spike in the meantime.

Hmm, okay, i could see the #147 is excluded using the #157. 
IDK whether this is right place to ask - what should be done to fix the spike build failure. 

on that note, which all repos (like spike) should be fixed before a PR is made in riscv-opcodes ?

**Comment by aswaterman** [comment]
The general rule is that Spike must build against the output of this repository.

Normally, adding new functionality to this repository poses no issues.  The problems arise when existing functionality is deleted.

Given there is no apparent plan to update Spike in accordance to #147 etc., we will revert those changes.  We'll happily re-accept them once there is a plan to make them work with Spike.

**Pull request merged**
