### PR TITLE
split arg_lut, causes, csr, csr32 from constants.py

### PR DESCRIPTION
**Pull request by sequencer**

### CODE REVIEW

**Review by aswaterman — COMMENTED** [review]
I agree this is an improvement, but I'd like @neelgala and others to weigh in before merging.

**Comment by sequencer** [comment]
Basically, the reason of this PR is I'm drafting a cleaner parser in Scala: https://github.com/sequencer/rvdecoderdb, which need to make all necessary information machine readable. I personally don't want to parse python script, thus move those these metadata into csv files.

**Comment by neelgala** [comment]
lgtm.. but you will need to resolve the conflicts to get this merged.

**Comment by sequencer** [comment]
@neelgala Fixed :)

**Comment by sequencer** [comment]
Can we get this in?

**Review by aswaterman — APPROVED** [review]

**Pull request merged**
