### PR TITLE
Narrow the fence and fence.i masks to match the ISA specification.

### PR DESCRIPTION
**Pull request by michaeljclark**
Before change:

 #define MATCH_FENCE 0xf
 #define MASK_FENCE  0x707f
 #define MATCH_FENCE_I 0x100f
 #define MASK_FENCE_I  0x707f

After change:

 #define MATCH_FENCE 0xf
 #define MASK_FENCE  0xf00fffff
 #define MATCH_FENCE_I 0x100f
 #define MASK_FENCE_I  0xffffffff

### CODE REVIEW

**Comment by michaeljclark** [comment]
Just noticed the mask for the fence instructions are a bit wide. Not sure of the reason...

**Comment by aswaterman** [comment]
Mmm? The spec says that the unused fields should be ignored, for compatibility with future fine-grained fences.

**Comment by michaeljclark** [comment]
OK. Can see that text now however the diagrams show zero values The patch leaves predecessor and successor open for "fence" and sets regs and immegiate to 0 for "fence.i" per the diagram.

What is the defined behaviour for calls with non-zero? This appears to be undefined behaviour.

If we apply this patch, the encoding space still remains free ... or does this have implications on the generated Chisel?

**Comment by aswaterman** [comment]
The unused bits are only allowed to make the fences finer grain, not coarser, so if implementations disregard them, everything's kosher.  There's no undefined behavior.  I think the right thing to do is not merge the patch -- doing so would cause future finer-grain fences to trap, which we don't want.

**Comment by michaeljclark** [comment]
OK. Understand. Closing the pull request.

**Pull request closed without merging**
