### PR TITLE
Add RV128I opcodes

### PR DESCRIPTION
**Pull request by pavelkryukov**

### CODE REVIEW

**Comment by aswaterman** [comment]
Given how speculative RV128 is at this time, I'd prefer not to merge this PR.  Others may disagree.

Separately, it looks like the LaTeX changes delete a column of zeros from the shift amount without amending the headers.  We should just back out the LaTeX changes for now if we do end up merging the PR.

**Comment by pavelkryukov** [comment]
How can we test LaTeX output? I could not find an instruction.

**Comment by pavelkryukov** [comment]
> Given how speculative RV128 is at this time, 

By the way, RV128C and RC128Q are presented in the repository already.

**Comment by aswaterman** [comment]
Yeah, I am also questioning whether they belong in the repo at this stage...

**Comment by pavelkryukov** [comment]
Is it possible put all of them into a branch, similarly to `riscv-bitmanip` branch?

**Comment by aswaterman** [comment]
I think that's a good idea.  I created a branch for rv128.  I'll close this PR, and you can open a new PR to that branch.

But before you do so, can you fix the LaTeX generation?  if you run `make instr-table.tex` on master, it should produce a bitwise-identical file before and after your changes.  In the current form of the PR, the shift instructions don't print correctly.

**Comment by pavelkryukov** [comment]
Yes, sure.

**Comment by pavelkryukov** [comment]
> In the current form of the PR, the shift instructions don't print correctly.

I see the only difference is the first column with one `0` bit less.
Shouldn't it be intended, as `shamt` might be 7 bits for RV128?

**Comment by pavelkryukov** [comment]
Oh, I see, it says "RV64I". Ok, I'll check what can be fixed here.

**Pull request closed without merging**
