### PR TITLE
Dump masks to C output

### PR DESCRIPTION
**Pull request by pavelkryukov**
These masks may be used to write parsers

### CODE REVIEW

**Comment by aswaterman** [comment]
I think ARG_LUT_ is not a great name prefix to put in an API. (For one, these are no longer lookup tables at this point.)

maybe something like RISCV_FIELD_? What do others think?

**Comment by neelgala** [comment]
`RISCV_FIELDS_` or `RISCV_ARGS_` is probably better

**Comment by pavelkryukov** [comment]
Other macros don’t have `RISCV_` prefix. Maybe `INSN_FIELD_`?

**Comment by neelgala** [comment]
`INSN_FIELD_` sounds fine

**Pull request merged**
