### PR TITLE
ci: use riscv-builders

### PR DESCRIPTION
**Pull request by mengzhuo**
To runs with riscv-builders, we need to install Github App
https://github.com/apps/riscv-builders

image

p.s It takes 9m to complete the CI, although it's ~30s with x86

### CODE REVIEW

**Comment by IIITM-Jay** [comment]
The reason checks are still running is that it is searching for the runner `riscv-builders` and it will search for indefinite time and that is forever. It will not be able to get the `riscv-builder` runner at all as it is acting as a **_self-hosted runner_** for this repository and it is trying to get that from GitHub Actions Environment. 

@aswaterman for this CI to get run, we have to configure and setup the same in a self-hosted runners. Currently, we are using the GitHub hosted runners which provides the OS(s) - Windows, Linux and Mac. Out of the provided OS as stated, we are running the CI on the ubuntu system of the latest version.

I am curious to know @aswaterman if you could throw some light on `riscv-builders`. As why it is beneficial to run and test this repository on `riscv-builders` and does it really necessary to run the builds on the same. Are the RISC-V related repositories suppose to be run on `riscv-builders` instead of the defualt OS provided by GitHub. 

I am in doubt as the hosted GitHub pages for `riscv-builders` says : _**"This project is very early alpha stage and NO WARRENTY."**_
https://riscv.builders/#sla

**Comment by mengzhuo** [comment]
@IIITM-Jay Thanks for the reply, what is requirement that we need for install a Github app? I might setup a topic on RISE TSC meeting on that. As for SLA, I can buy a sever rack in data center to improve SLA.

@aswaterman The main reason is I've got PR rejected by some open source projects by "what kind of CI that runs RISCV?" https://github.com/goreleaser/goreleaser/pull/5196#issuecomment-2408587609, https://github.com/open-telemetry/opentelemetry-go/pull/5420#issuecomment-2135414810, I think it's time to leading by example or ["dogfooding"](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) now.

**Comment by IIITM-Jay** [comment]
> This software is meant to run on any POSIX system regardless of ISA, so we should use whatever CI system is cheapest/easiest to use/etc.

@aswaterman Yes, I completely agree with this. We should focus on the cheapest, and the easiest one to maintain on a longer run thereby using the best and standard practices. Additionally, we should also focus on minimizing the time it takes to run the CI builds to completion as higher times are not the best time acceptable for the CI to take. Here, as above, it took **_9 minutes_** for the builds to complete _(as stated in the screenshot)_ which is not quite good enough.

**Comment by aswaterman** [comment]
Yeah, we're on the same page, @IIITM-Jay.

@mengzhuo I appreciate what you're trying to do, but this is not the right place to do it.  The focus should be on software that actually runs on RISC-V processors.  For the time being, this is not that software.

**Pull request closed without merging**
