### PR TITLE
Remove duplicate code

### PR DESCRIPTION
**Pull request by pavelkryukov**

### CODE REVIEW

**Comment by neelgala** [comment]
once #120 is merged @pavelkryukov can you enable the testing for overlapping args in this PR

**Comment by pavelkryukov** [comment]
#120 has test enabled already

**Comment by neelgala** [comment]
@aswaterman LGTM for merging

**Comment by aswaterman** [comment]
I'm always happy to delete code!

**Comment by aswaterman** [comment]
However, please fix the merge conflicts and rebase, @pavelkryukov

**Comment by pavelkryukov** [comment]
Done

**Comment by pavelkryukov** [comment]
reminder...

**Comment by neelgala** [comment]
LGTM

**Pull request merged**
